# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ca1d8332eb8434a5c14c86c4737d994436a8d82179340b360f3004d7700e5f11437349cb26a252315f443a69e7621c6a2229b0ae1e6c4303900e56be29942f

test:
  secret_key_base: 81da840a14add0c29cf15c89b61d4b01338e5ca722ee5955d51328a7edc47f96ac3f23587b48ab98e89efc1a1060cab60edd4c3c19627bededc5b2cdd794e874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
